#---------PACMAN---------#
PACMAN = 
PACMAN_ARRIBA =
PACMAN_ABAJO =
PACMAN_IZQUIERDA =
PACMAN_DERECHA =

#---------FANTASMA ROJO---------#
FANTASMA_ROJO_ARIBA =
FANTASMA_ROJO_ABAJO =
FANTASMA_ROJO_IZQUIERDA =
FANTASMA_ROJO_DERECHA =

#---------FANTASMA AZUL---------#
FANTASMA_AZUL_ARIBA =
FANTASMA_AZUL_ABAJO =
FANTASMA_AZUL_IZQUIERDA =
FANTASMA_AZUL_DERECHA =

#---------FANTASMA NARANJA---------#
FANTASMA_NARANJA_ARIBA =
FANTASMA_NARANJA_ABAJO =
FANTASMA_NARANJA_IZQUIERDA =
FANTASMA_NARANJA_DERECHA =

#---------FANTASMA ROSA---------#
FANTASMA_ROSA_ARIBA =
FANTASMA_ROSA_ABAJO =
FANTASMA_ROSA_IZQUIERDA =
FANTASMA_ROSA_DERECHA =

#---------MUROS---------#

