#---------PACMAN---------#
PACMAN = 
PACMAN_ARRIBA =
PACMAN_ABAJO =
PACMAN_IZQUIERDA =
PACMAN_DERECHA =

#---------FANTASMA ROJO---------#
FANTASMA_ROJO_ARIBA =
FANTASMA_ROJO_ABAJO =
FANTASMA_ROJO_IZQUIERDA =
FANTASMA_ROJO_DERECHA =

#---------FANTASMA AZUL---------#

#---------FANTASMA NARANJA---------#

#---------FANTASMA ROSA---------#
